### ISSUE TITLE
scala-cli-action always install Java, even if JAVA_HOME is defined

### ISSUE THREAD

**Issue by adamw** [VirtusLab/scala-cli#3013]
The action shouldn't install Java if one is already installed, but this doesn't happen. That's probably because the default value for `jvm` is `temurin:17`, so that's always installed, unless the option is overriden.

![image](https://github.com/VirtusLab/scala-cli/assets/60503/2af9a6d2-1567-4def-adcc-458baa328026)

The work-around is to provide an empty value for `jvm`:

```
    - name: Install scala-cli
      uses: VirtusLab/scala-cli-setup@main
      with:
        jvm: ''
```
