### ISSUE TITLE
Provide a GitHub action for installing scala-cli

### ISSUE THREAD

**Issue by armanbilge** [VirtusLab/scala-cli#662]
Should be pretty simple, the whole action can even be something like this probably:

```yaml
name: 'Install scala-cli'
description: 'Install scala-cli'
author: 'Virtus Lab'
runs:
  using: 'composite'
  steps:
    - run: |
        curl -s --compressed "https://virtuslab.github.io/scala-cli-packages/KEY.gpg" | sudo apt-key add -
        sudo curl -s --compressed -o /etc/apt/sources.list.d/scala_cli_packages.list "https://virtuslab.github.io/scala-cli-packages/debian/scala_cli_packages.list"
        sudo apt update
        sudo apt install scala-cli
      if: runner.os == 'Linux'
    - run: brew install Virtuslab/scala-cli/scala-cli
      if: runner.os == 'macOS'
```

Sorry, not sure what to do for windows.

Thanks!

**Comment by ckipp01** [comment]
@armanbilge another option is to use `coursier/setup-action`. I do this [here](https://github.com/ckipp01/ents/blob/main/.github/workflows/CI.yml) and it works pretty well.

**Comment by armanbilge** [comment]
@ckipp01 aha, `apps: scala-cli scalafmt` is exactly what I needed. Thanks for the pointer!

**Comment by ckipp01** [comment]
btw you might not even need `scalafmt` but can instead use `scala-cli format`. I only had that in there since before `--check` didn't work with `scala-cli`. It works with the latest `scala-cli`, I just haven't updated this yet.

**Comment by lwronski** [comment]
Hi @ckipp01  @armanbilge  you can try to use `VirtusLab/scala-cli-setup` -  https://github.com/VirtusLab/scala-cli-setup. It is a fork of `coursier/setup-action` where we enforce to install `scala-cli`.

There are also available functions from `coursier/setup-action` such as `apps` and `jvm`

```
jobs:
   scala-cli:
      runs-on: ${{ matrix.OS }}
      strategy:
        fail-fast: false
        matrix:
          OS: ["ubuntu-latest", "macos-latest", "windows-latest"]
      timeout-minutes: 120
      steps:
       - uses: actions/checkout@v2
       - uses: coursier/cache-action@v6
       - uses: VirtusLab/scala-cli-setup@main
       - run: scala-cli
```
