### ISSUE TITLE
"Github Action" snippet doesn't display newlines

### ISSUE THREAD

**Issue by kubukoz** [VirtusLab/scala-cli#980]
**Version(s)**

0.1.5

**Describe the bug**

The website shows the snippet in an unreadable form:

<img width="862" alt="image" src="https://user-images.githubusercontent.com/894884/166923399-68068ecb-bdf1-477f-a463-9bf47431e090.png">

This also affects copy-paste.

**To Reproduce**

Go to https://scala-cli.virtuslab.org/docs/overview, click "GitHub Actions"

**Expected behaviour**

The code displays like here

```yml
steps:
  - uses: coursier/cache-action@v6
  - uses: VirtusLab/scala-cli-setup@main
```
